Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 100

#begin ruby 1.8 support
Style/HashSyntax:
  EnforcedStyle: hash_rockets

Style/Lambda:
  Enabled: false

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

Style/EachWithObject:
  Enabled: false
