language: ruby
rvm:
  - 2.2.5
  - 2.3.1
  - 2.4.1
  - jruby-9.0.5.0
  - rbx

before_install:
  - gem install bundler

bundler_args: --without development

script:
  - bundle exec rspec

matrix:
  allow_failures:
    - rvm: rbx
