version: 2

multi-ecosystem-groups:
  app-dependencies:
    schedule:
      interval: "monthly"
      time: "06:00"
      day: "monday"
      timezone: "America/Detroit"
    commit-message:
      prefix: "Monthly dependency updates: "

  container-updates:
    schedule:
      interval: "cron"
      cronjob: "0 6 3 4 *" #April 3 at 6AM
      timezone: "America/Detroit"
    commit-message:
      prefix: "Annual container update: "

updates:
  # For GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "app-dependencies"
    patterns: ["*"]

  # For Bundler/Ruby
  - package-ecosystem: "bundler"
    directory: "/"
    multi-ecosystem-group: "app-dependencies"
    patterns: ["*"]

  # For Docker
  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "container-updates"
    patterns: ["*"]

  # For Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    multi-ecosystem-group: "container-updates"
    patterns: ["*"]
