  # Configure what service plugins are used by Umlaut. This skeleton file
  # has been generated into your app to help you get started.
  #
  # If a service has "disabled:true", it's currently turned off.
  #
  # Some services require local api key or connection details as config.
  # Most services take other options for custom configuration too, not
  # all options are neccesarily listed as examples here, see source
  # or source-generated docs for more info.
  #
  # The services in the 'default' group are loaded every time.
  # You can optionally create other groups of services, that can be loaded
  # by URL query params, or based on other request params. More info?
  #
  # This file is run through ERB, so you can use <%= %> tags for dynamic
  # ruby content if you like.
  #

default:
    services:

      Alma:
        type: Umlaut::Alma::Service
        priority: 2
        base_url: https://na04.alma.exlibrisgroup.com/view/uresolver
        institution: 01UMICH_INST
        # campus_code: UMICH ?

      # SFX has pubmed lookup built in, so this service not generally
      # needed with SFX, but included here as an example of it's availability
      Pubmed:
        disabled: true
        priority: 0

      # Priority 3
      Umlaut::Mirlyn::Service:
        type: Umlaut::Mirlyn::Service
        display_name: Mirlyn
        help:
          label: Problems accessing fulltext
          base:
            host: umich.qualtrics.com
            path: /SE/
            query:
              SID: SV_2broDMHlZrBYwJL
              LinkModel: unknown
              ReportSource: MGetIt
              DocumentID: unknown
        holding_feed:
          label: Mirlyn
          base:
            host: mirlyn.lib.umich.edu
            path: /Search/SearchExport
        holding_search:
          label: Search the catalog
          base:
            host: search.lib.umich.edu
            path: /catalog
        document_delivery:
          label: Document Delivery
          base:
            host: ill.lib.umich.edu
            path: /illiad/illiad.dll
        priority: 3

      ThreeSixtyLink:
        disabled: true
        type: ThreeSixtyLink
        display_name: MGetIt
        base_url: http://dl2af5jf3e.openurl.xml.serialssolutions.com/openurlxml
        open_timeout: 90
        read_timeout: 90
        priority: 2

      SFX:
        type: Sfx
        disabled: true
        display_name: Find It
        base_url: YOUR_SFX_BASE_URL
        priority: 3

      # We have GoogleBookSearch running early because it can take a bare ISBN
      # and look up bibliographic metadata, which is useful to happen early.
      # By running at the same priority as SFX, 3, it will run concurrently
      # and maximize fast response time. You could also have it run before SFX,
      # if you needed SFX to have the enhanced metadata from GoogleBookSearch.
      #
      # It can also find cover images, abstracts, and links to
      # previews and search-inside-the-book. You can turn
      # each of those off if you want.
      GoogleBookSearch:
        type: GoogleBookSearch
        disabled: false
        priority: 3
        api_key: ''
        referent_enhance: true
        fulltext: true
        cover_image: true
        abstract: true
        web_links: true

      # blind link to price comparison site AllBooks.com.
      # just a blind link with no API pre-check, will be near
      # instantaneous to calculate.
      AllBooksDotCom:
        disabled: true
        type: AllBooksDotCom
        priority: 3



      # Priority c  : Background

      # Suggest that any background services that may produce `fulltext` responses
      # be put in the same bg wave, to increase perceived responsiveness
      # by ending the spinner in the fulltext area.



      CoverThing:
        type: CoverThing
        disabled: true
        developer_key: YOUR_LT_KEY
        priority: c
        # Pre-empted by says if we already have a cover_image response
        # from somewhere else that runs earlier, don't run this.
        preempted_by:
          existing_type: cover_image

      ElsevierCover:
        disabled: true
        type: ElsevierCover
        priority: c

      UlrichsCover:
        disabled: true
        type: UlrichsCover
        priority: c

      InternetArchive:
        disabled: true
        display_name: the Internet Archive
        type: InternetArchive
        priority: c
        # disable audio results? uncomment:
        #num_results_for_types:
        #  audio: 0

      HathiTrust:
        disabled: true
        type: HathiTrust
        priority: c
        # Uncomment to link through this 'internal' URL instead
        # of following permalinks. jrochkind does this to use
        # a WAYFless shibboleth login with EZProxy.
        #direct_link_base: 'https://babel.hathitrust.org/shcgi/'
        #
        # This next says:
        # Don't add HathiTrust fulltext if there's already a
        # GoogleBookSearch fulltext. Still add other HT response
        # types.
        preempted_by:
          self_type: fulltext
          existing_service: GoogleBookSearch
          existing_type: fulltext






      # Priority d

      # You might be able to pack a lot of these in 'c' too, simultaneously.
      # But to avoid trying to do too much at once, we put most 'see also'
      # type services later, in 'd'.

      Ulrichs:
        disabled: true
        display_name: "Ulrich's Directory"
        type: UlrichsLink
        priority: d

      EmailExport:
        disabled: true
        type: EmailExport
        priority: d

      TxtHoldingExport:
        disabled: true
        type: TxtHoldingExport
        priority: d

      ScopusCitations:
        type: Scopus
        disabled: true
        priority: d
        json_api_key: YOUR_SCOPUS_API_KEY
        partner_id: YOUR_SCOPUS_PARTNER_ID
        link_salt_key: "YOUR_SCOPUS_LINK_SALT_KEY"

      # Web of Science API has no api key, but your
      # IP needs to be registered with them. See source docs
      # for how.
      IsiCitations:
        disabled: true
        type: Isi
        priority: d

      # Thomson JCR LAMR api has no api key, but your
      # IP needs to be registered with them. Same registraiton
      # as for ISI WoK generally.
      Jcr:
        disabled: true
        type: Jcr
        priority: d



      # Worldcat scraper can be quite slow, move it to wave 'd' to avoid
      # holding up wave 'c'
      Worldcat:
        disabled: true
        display_name: OCLC Worldcat.org
        type: Worldcat
        priority: d
        # suppress_precheck says don't actually screen-scrape to
        # see if the link is good, just link blindly. Mostly works
        # for WorldCat, avoids the performance hit.
        suppress_precheck: true


      WorldcatIdentities:
        disabled: true
        type: WorldcatIdentities
        priority: d
        # Turn off certain response types:
        #note_types: false
        #wikipedia_link: false
        #openurl_widely_held: false
        #require_identifier: true


      # GPO is kind of experimental, it doesn't work great, but IF an
      # OpenURL includes a sudoc call number or other GPO identifiers,
      # will try to link to full text via GPO catalog scrape.
      Gpo:
        type: Gpo
        disabled: true
        priority: e
        #preempted_by:
        #  - existing_type: fulltext
        #  - existing_type: fulltext_title_level


      ####
      # Link out filters: Effect what happens when a user clicks
      # on an Umlaut link to a third party source. Link out filters
      # can operate to change where link goes or execute side effects
      # on click.
      ####

      # Redirect outgoing links through EZProxy
      EZProxy:
        type: Ezproxy
        disabled: true
        task: link_out_filter
        proxy_server:  HOSTNAME_OF_YOUR_EZPROXY
        # By default, will pre-check with EZProxy api and
        # only send links through EZProxy that are proxyable.
        # requires proxy_password to be set.
        # optionally, set precheck_with_api false, and the EZProxy
        # api won't be used, ALL links go through EZProxy. You may
        # have EZProxy itself set to transparently redirect non-proxyable
        # URLs back to non-proxied version.
        #
        #precheck_with_api: false
        priority: 5
        proxy_password: YOUR_EZPROXY_API_PWD
        # Want to exclude certain hostnames from being directed through EZProxy?
        # list them in array here:
        #exclude: [ host.unversity.edu, otherhost.somewhere.com]

